### ISSUE TITLE
warning supression on php 8.1

### ISSUE THREAD

**Issue by jostreff** [bitslip6/bitfire#28]
https://github.com/bitslip6/bitfire/blob/8ec0c3ea7460de7b4b57a0eda345b2d9929d0698/firewall/src/server.php#L665

It's better this line to be: 
$effect->file(new FileMod(\BitFire\WAF_ROOT . "uninstall_lock", "locked", 0, time() + (int)
ini_get("user_ini.cache_ttl")));

**Comment by bitslip6** [comment]
Thanks for the note.  I'll check in this fix tonight!

**Comment by bitslip6** [comment]
resolved
